/* config.js — deployment configuration and grid geometry.
   Change only this file when switching environments or grid resolutions.

   Phase 1 (now):   relative paths — works with any HTTP server or CloudFront
   Phase 2 (later): swap to absolute API URLs + populate getAuthHeaders()

   Load order: first script after CDN libs, before everything else. */

/* ── App version — SINGLE SOURCE OF TRUTH ─────────────────────────────────
   The whole app shares ONE version. It is shown in the header (site-nav.js) and is the
   cache-buster for every versioned asset: data PNGs use `?v=' + APP_VERSION` below, and JS/CSS
   in every page's <script>/<link> use the literal `?v=0.9.10` (kept in lockstep with this).
   POLICY: bump the patch number on EVERY change (0.9.10 -> 0.9.11 -> ... 0.9.196 ...) while the
   0.9 dev branch is open; when 0.9 is declared stable, close it and go to the 1.0.0 release
   candidate. To bump: change APP_VERSION here AND `perl -i -pe 's/\?v=[\d.]+/?v=NEW/g' *.html`.
   See the dev guide "Versioning". */
const APP_VERSION = '1.2.4';
const _v = '?v=' + APP_VERSION;   // data-PNG cache-buster (JS/CSS busters live literally in the HTML)

/* ── PV model physical constants — SINGLE SOURCE OF TRUTH ──────────────────
   Faiman module-temperature coefficients for FREE-STANDING crystalline silicon, taken VERBATIM from
   the vendored PVGIS source (assets/pvgis/pvgis/api/power/efficiency_coefficients.py, "cSi 2025" set,
   indices [7] and [8]). Cell temp: T_cell = T_air + G_eff / (U0 + U1·wind).
   NEVER hard-code 26.9 / 6.2 anywhere again — reference these. Used by formulas.js (tcell_faiman),
   yield-engine.js, the Faiman UI defaults (yield.html / yield-ui.js), and the docs. */
const FAIMAN_U0 = 26.9;   // W/m²K        — constant (radiative + free-convective) loss coefficient
const FAIMAN_U1 = 6.2;    // W/m²K/(m/s)  — wind (forced-convective) loss coefficient

/* ── Economic-analysis defaults — SINGLE SOURCE OF TRUTH (economics.html) ───
   The prices table (js/electricity-prices.js) is retail EUR/kWh incl. taxes = e1. To prefill the
   e1/e2/C_FV inputs in the selected currency we need a coarse, manually-maintained FX table and a
   turnkey €/Wp benchmark. These are deliberately approximate (refresh when the price table is
   re-run); the user can always override every prefilled value. */
const FX_PER_EUR  = { EUR: 1, RON: 4.97, USD: 1.08 };   // units of currency per 1 EUR (approx, manual)
const ECON_EUR_PER_WP = 1.1;   // €/Wp turnkey residential PV (equipment + mounting + labour + permits), editable per project
const ECON_E2_FACTOR  = 0.5;   // injected-surplus price e2 as a fraction of supply price e1 (course example ≈0.46)
const ECON_DEFAULT_N    = 20;  // analysis horizon (years) — course minimum
const ECON_DEFAULT_RATE = 7;   // average market interest / discount rate (%)
const ECON_BOM_UPLIFT   = 25;  // % uplift on the equipment BoM (modules+inverters+batteries) for the "from selected
                               // components" C_FV estimate - covers consumables/BoS/cabling + margin, WITHOUT mounting
                               // /labour (manoperă). The general cfvNote reminds a full C_FV adds manoperă + avize.
const ECON_SELFCONS_RATE = 40; // default self-consumption rate Rac (%) for a household without storage (30 typical / 50 daytime-heavy / 70-90 with battery)
const ECON_DAY_FRACTION  = 35; // default daytime consumption share (%) for the day/night self-consumption model
// Expert (with-battery) autoconsum sim - typical-day windows used to power-limit the daily charge/discharge
// (a monthly-climatology proxy for an hourly model): effective solar hours to fill the battery, night hours
// to draw it down. Capacity (kwhUsable) is the dominant constraint; these only bind for small/low-power packs.
const ECON_BAT_SOLAR_H = 5;    // effective peak-sun hours/day the surplus can charge the battery
const ECON_BAT_NIGHT_H = 12;   // night hours over which the battery covers the evening/night load
// Default residential monthly consumption shape (fractions of the annual total, sums to 1) - a
// winter-heavy European household profile (heating/lighting). Used by consumption.html DETAILED mode,
// which has no per-month input, so economics' monthly self-consumption (lunar/zinoapte) has a real
// seasonal curve instead of a flat annual/12. Simple mode uses the user's own 12 monthly entries.
const CONSUMPTION_SEASONAL_PROFILE = [0.10, 0.09, 0.09, 0.08, 0.075, 0.07, 0.07, 0.07, 0.075, 0.085, 0.095, 0.10];

/* ── Elevation: 8-bit grayscale PNG, global grid ──────────────────────────
   Generated by: scripts/generate-elevation-png.js (source: ETOPO2022)
   Encoding: pixel = round(max(0, elev_m) / ELEV_SCALE), decode: elev_m ≈ pixel × ELEV_SCALE
   Decoded by: js/elevation-png.js → Int16Array (metres, land ≥ 0, ocean = 0)

   ┌─ Switch resolution here ──────────────────────────────────────────────
   │  0.5°×0.5° (prev):    ELEV_NLATS=361,  ELEV_NLONS=721,  ELEV_STEP=0.5, file=elevation05.png
   │  0.1°×0.1° (current): ELEV_NLATS=1801, ELEV_NLONS=3601, ELEV_STEP=0.1, file=elevation.png
   └────────────────────────────────────────────────────────────────────── */
const ELEV_NLATS   = 1801;
const ELEV_NLONS   = 3601;
const ELEV_STEP    = 0.1;
const ELEV_SCALE   = 25;      // metres per pixel step
const ELEV_LAT_MIN = -90;
const ELEV_LON_MIN = -180;

/* ── Kt clearness index: 8-bit PNG, monthly Kt_cs per cell ───────────────
   Generated by: scripts/generate-kt-grid-1deg.js → generate-kt-png.js
   Encoding: pixel = round(Kt_cs × 100), decode: Kt_cs = pixel / 100
   Decoded by: js/kt-png.js → Uint8Array

   ┌─ Switch BASE resolution here ─────────────────────────────────────────
   │  5°×5°  (legacy):  KT_NLATS=37,   KT_NLONS=73,   KT_STEP=5,   file=kt5.bin
   │  1°×1°  (active):  KT_NLATS=181,  KT_NLONS=361,  KT_STEP=1,   file=kt1.png  ← base
   └──────────────────────────────────────────────────────────────────────
   Hybrid grid: a global 1° base (kt1.png) + small per-country 0.1° hi-res TILES (KT_TILES
   below). resolveKt() in kt-grid.js prefers a tile when the point is inside its bbox, else
   bilinear-upsamples the 1° base. A coarse global product can't resolve sub-10 km valley
   microclimate (PVGIS-ERA5 at Brasov = +11.5% vs SARAH-3, same as the 1° smear), so the only
   thing that fixes a region is a 0.1° SARAH-3 tile - and storing that GLOBALLY at 0.1° would be
   ~4.5 MB of mostly-redundant upsample. Per-country tiles give identical output at ~20 KB each. */
/* BASE = CM SAF CLARA-A3 GLOBAL 0.25° Kt (data/kt-global.png), 720×1440×12, cell-centred grid
   (origin -90/-180, resampled from CLARA's native -89.875 cell centres). Kt_cs = CLARA SIS / Hofierka(CLARA-SISCLS-calibrated TL). Replaces the
   old 1° kt1.png (181×361, latMin -90): single global satellite CDR, 4× finer, real data to the poles.
   (Switch back to the 1° base: KT_NLATS=181 KT_NLONS=361 KT_STEP=1 KT_LAT_MIN=-90 KT_LON_MIN=-180 + ktUrl=kt1.png.) */
const KT_NLATS   = 720;
const KT_NLONS   = 1440;
const KT_STEP    = 0.25;
const KT_NMONTHS = 12;
const KT_LAT_MIN = -90;
const KT_LON_MIN = -180;

/* ONE CM SAF SARAH-3 tile over the 0.25° CLARA global base (deliberately a SINGLE tile, no nesting):
   NATIVE 0.05° over Europe, lat 34-58 / lon -11..38 (cell centres on the SARAH native grid x.025/x.075,
   so the origin is 33.975/-11.025). Clipped to Denmark in the N, the UK/Ireland shore in the W, and ~Crimea
   in the E - the disc edges (far N, Atlantic, and the Caspian/Volga E) are oblique + noisy in SARAH's
   geostationary view, so they're left to the CLARA polar base, which is BETTER at high latitude / off-disc. 2005-2023, period-matched to PVGIS-SARAH3;
   Kt_cs = SARAH all-sky SIS / Hofierka(CLARA-calibrated TL), dead-pixel free. WHY native 0.05° (not 0.1°):
   a 0.1° cell over a mountain valley mixes the valley with brighter/snowier peaks and reads ~3-6% high in
   winter (Brasov, Alps, Pyrenees); the native cell isolates it. Replaces the coarse 0.25° CLARA AVHRR base
   over the continent (which read -3..-4% low at Roma/Wien/Budapest/Berlin). resolveKt() uses the tile
   in-bbox, else the base. Validated vs PVGIS-SARAH3 with the PVGIS-calibrated beam/diffuse split
   (yield-engine.js liuJordanKd). Pipeline: eumdac SISmm -> sarah3-to-sis-native.py 34 58 -11 45 2005 2023
   sis-eu-005 -> build-kt-europe-sarah.js sis-eu-005 kt-europe-01.png. */
/* DROPPED for load time (2026-06): the 1 MB SARAH3 Europe tile was retired once the global CLARA base was
   PVGIS-de-biased (the bed-leveling mesh) - it then only bought ~0.3pp mean irradiance over Europe (mostly the
   native 0.05° Kt resolution in Carpathian/Alpine valleys, partly covered now by the terrain-horizon tiles).
   To re-add: restore the row below (the file is still in data/, regenerable via the eumdac SARAH3 pipeline). */
const KT_TILES = [
  // { iso: 'eu', url: 'data/kt-europe-01.png' + _v, latMin: 33.975, lonMin: -11.025, nlats: 483, nlons: 983, step: 0.05 },
];

/* ── Terrain-horizon tiles - LAZY-LOADED by location, fixed 1°×1° convention grid ─────────────────
   Per-cell terrain horizon (A azimuth layers, deg) from AWS Terrarium DEM. Tiles live at
   `data/horizon/<lat>_<lon>.png` (SW-corner SIGNED integers, e.g. 45_6, -23_130). The geometry is
   DERIVED from the tile id - there is NO manifest. horizon-grid.js lazy-fetches the tile covering the
   user's location on demand; a 404 means flat/ocean -> no horizon (most of the planet). Only mountainous
   land tiles are generated + shipped. Built by scripts/build-horizon-tile.js --tile <lat> <lon>. */
const HORIZON_DEG  = 1;          // tile extent (degrees)
const HORIZON_STEP = 0.01;       // serving cell (~1.1 km) - fine enough to LOOK UP a ~90m-computed horizon
const HORIZON_A    = 24;         // azimuth layers (every 15°)
const HORIZON_BASE = 'data/horizon/';            // + '<lat>_<lon>.png' + _v
const HORIZON_INDEX = 'data/horizon-index.png';  // tiny global bitmask (which 1° tiles exist) -> no 404s on flat land

/* ── Temperature: 8-bit grayscale PNG, monthly 2m air temperature ─────────
   Generated by: scripts/generate-temperature-png.js (source: NASA POWER)
   Encoding: pixel = temp_°C + 128, decode: temp_°C = pixel − 128
   Decoded by: js/temp-png.js → Int8Array (signed °C)
   PNG layout: width=TEMP_NLONS×TEMP_NMONTHS (876), height=TEMP_NLATS (months side-by-side)
   Cell access: data[(m * TEMP_NLATS + r) * TEMP_NLONS + c]  (decoded by temp-png.js)

   ┌─ Switch resolution here when temperature.png (1°×1°) is ready ──────────
   │  5°×5°  (current):  TEMP_NLATS=37,  TEMP_NLONS=73,  TEMP_STEP=5, file=temp5.png
   │  1°×1°  (pending):  TEMP_NLATS=181, TEMP_NLONS=361, TEMP_STEP=1, file=temp1.png
   └──────────────────────────────────────────────────────────────────────── */
const TEMP_NLATS   = 181;
const TEMP_NLONS   = 361;
const TEMP_STEP    = 1;
const TEMP_NMONTHS = 12;
const TEMP_LAT_MIN = -90;
const TEMP_LON_MIN = -180;

/* ── Linke turbidity: 8-bit PNG, monthly TL per cell ─────────────────────
   Generated by: scripts/generate-tl-grid.js (source: NASA POWER ghiFull)
   Encoding: pixel = round(TL × 20), decode: TL = pixel / 20
   Decoded by: js/tl-png.js → Uint8Array

   ┌─ Switch resolution here ──────────────────────────────────────────────
   │  5°×5° (legacy):  TL_NLATS=37,  TL_NLONS=73,  TL_STEP=5, file=tl5.png
   │  1°×1° (current): TL_NLATS=181, TL_NLONS=361, TL_STEP=1, file=tl1.png  ← active
   └────────────────────────────────────────────────────────────────────── */
const TL_NLATS   = 181;
const TL_NLONS   = 361;
const TL_STEP    = 1;
const TL_NMONTHS = 12;
const TL_LAT_MIN = -90;
const TL_LON_MIN = -180;

/* ── Wind speed: 8-bit PNG, monthly WS2M at 2 m (NASA POWER) ─────────────
   Generated by: scripts/generate-wind-grid-1deg.js (1°×1°)
              or scripts/generate-wind-grid.js       (5°×5° legacy)
   Encoding: pixel = round(clamp(ws, 0, 25.4) × 10), decode: ws_m_s = pixel / 10
   Decoded by: js/wind-png.js → Uint8Array
   PNG layout: width=WIND_NLONS×WIND_NMONTHS, height=WIND_NLATS (months side-by-side)
   Cell access: data[(m * WIND_NLATS + r) * WIND_NLONS + c]  (decoded by wind-png.js)

   ┌─ Switch resolution here ──────────────────────────────────────────────
   │  5°×5° (legacy):  WIND_NLATS=37,  WIND_NLONS=73,  WIND_STEP=5, file=wind5.png
   │  1°×1° (active):  WIND_NLATS=181, WIND_NLONS=361, WIND_STEP=1, file=wind1.png
   └────────────────────────────────────────────────────────────────────── */
const WIND_NLATS   = 181;
const WIND_NLONS   = 361;
const WIND_STEP    = 1;
const WIND_NMONTHS = 12;
const WIND_LAT_MIN = -90;
const WIND_LON_MIN = -180;

/* ── Main config ── */
/* ── Extreme wind: 8-bit grayscale PNG, fundamental basic wind velocity vb,0 ──────
   Generated by: scripts/generate-extremewind-grid.js (EN1991-1-4 National Annexes / national
   codes; sub-zoned per province / municipality / NA-zonation where sourced, else one
   representative vb,0 per country - indicative screening map, NOT the legal map).
   Encoding: pixel = round(vb0_m_s · EXTREMEWIND_SCALE), decode: vb0 = pixel / EXTREMEWIND_SCALE
   Decoded by: js/extremewind-png.js → Float32Array (m/s, 0 = no data) */
const EXTREMEWIND_NLATS   = 1801;
const EXTREMEWIND_NLONS   = 3601;
const EXTREMEWIND_STEP    = 0.1;
const EXTREMEWIND_SCALE   = 4;       // 0.25 m/s per pixel step
const EXTREMEWIND_LAT_MIN = -90;
const EXTREMEWIND_LON_MIN = -180;

const CONFIG = {
  elevationUrl: 'data/elevation.png' + _v,
  ktUrl:        'data/kt-global.png' + _v, // 0.25° CLARA-A3 global base, PVGIS-de-biased (the only Kt grid now; KT_TILES retired)
  tempUrl:      'data/temp1.png' + _v,   // 1°×1° NASA POWER monthly 2m air temperature
  tlUrl:        'data/tl1.png' + _v,     // Linke turbidity 1°×1° — high-res
  windUrl:      'data/wind1.png' + _v,   // 1°×1° NASA POWER WS2M
  extremeWindUrl: 'data/extremewind1.png' + _v,   // 1°×1° EN1991-1-4 vb,0 (per-country, crude v1)
};

/* ── Viz pages default overlay opacity (0–1) ──────────────────────────────
   Controls the initial alpha of grid overlays in *Viz.html pages.
   Users can still adjust via the Opacity slider at runtime. */
const VIZ_OPACITY = 0.35;

/* Return auth headers for every grid fetch.
   Phase 1: empty — data is public on CloudFront.
   Phase 2: { 'Authorization': 'Bearer ' + getSessionToken() } */
function getAuthHeaders() {
  return {};
}
