/* elevation-png.js — 8-bit grayscale PNG loader for elevation grids.
   Decodes data/elevation.png (generated by scripts/generate-elevation-png.js):
     - 8-bit grayscale, Sub filter (type 1) per row, IDAT = zlib-compressed
     - Encoding: pixel_value = round(max(0, elevation_m) / ELEV_SCALE)
     - Decode:   elevation_m ≈ pixel_value × ELEV_SCALE

   Uses fetch + DecompressionStream('deflate') — no external deps, no canvas needed.
   Depends on: config.js for ELEV_SCALE. */

/**
 * Fetch and decode an 8-bit grayscale elevation PNG.
 * @param {string} url — relative or absolute URL
 * @param {object} [headers] — optional request headers
 * @returns {Promise<Int16Array>} elevation in metres, row-major (north→south)
 */
async function loadElevationPng(url, headers = {}) {
  /* ── 1. Fetch ── */
  const resp = await fetch(url, { headers });
  if (!resp.ok) throw new Error(`loadElevationPng: HTTP ${resp.status} for ${url}`);
  const buf  = await resp.arrayBuffer();
  const view = new DataView(buf);
  const u8   = new Uint8Array(buf);

  /* ── 2. Parse PNG dimensions from IHDR ── */
  // Layout after 8-byte magic: [4-len][4-"IHDR"][width4][height4][...]
  const width  = view.getUint32(16);
  const height = view.getUint32(20);

  /* ── 3. Collect IDAT payload(s) ── */
  const idatParts = [];
  let obfuscated = false;                     // set if the PNG carries the 'obf' tEXt marker
  let pos = 33;   // 8(magic) + 4+4+13+4(IHDR chunk) = 33
  while (pos + 8 <= buf.byteLength) {
    const chunkLen  = view.getUint32(pos);
    const chunkType = String.fromCharCode(u8[pos+4], u8[pos+5], u8[pos+6], u8[pos+7]);
    if (chunkType === 'IEND') break;
    if (chunkType === 'IDAT') {
      idatParts.push(u8.slice(pos + 8, pos + 8 + chunkLen));
    } else if (chunkType === 'tEXt' && u8[pos+8] === 111 && u8[pos+9] === 98 && u8[pos+10] === 102) {
      obfuscated = true;
    }
    pos += 4 + 4 + chunkLen + 4;
  }

  /* ── 4. Concatenate IDAT ── */
  const idatLen = idatParts.reduce((s, c) => s + c.length, 0);
  const idat    = new Uint8Array(idatLen);
  let off = 0;
  for (const part of idatParts) { idat.set(part, off); off += part.length; }

  /* ── 5. Decompress: zlib DEFLATE (RFC 1950) → raw filtered scanlines ──
     Standard PNG uses zlib-wrapped DEFLATE; 'deflate' in DecompressionStream
     correctly means RFC 1950 in all modern browsers (Chrome 80+, FF, Safari). */
  const stream = new Blob([idat]).stream().pipeThrough(new DecompressionStream('deflate'));
  const rawBuf = await new Response(stream).arrayBuffer();
  const raw    = new Uint8Array(rawBuf);

  /* ── 6. Reconstruct Sub filter (BPP=1) and scale to metres ── */
  // Each scanline: 1 filter byte (always 1=Sub) + width pixel bytes
  // Sub reconstruct: out[i] = (filtered[i] + out[i-1]) & 0xFF
  const scanStride = 1 + width;
  let img = new Uint8Array(width * height);
  for (let row = 0; row < height; row++) {
    const base = row * scanStride;
    let prev = 0;
    for (let col = 0; col < width; col++) {
      const px = (raw[base + 1 + col] + prev) & 0xFF;
      prev = px;
      img[row * width + col] = px;
    }
  }

  /* Reverse the grid obfuscation (only when the PNG is marked) */
  if (obfuscated) {
    if (typeof GridObfus === 'undefined') throw new Error('loadElevationPng: grid-deshuffle.js must load before an obfuscated grid');
    img = GridObfus.decode(img, width, height);
  }

  const result = new Int16Array(width * height);
  for (let i = 0; i < result.length; i++) result[i] = img[i] * ELEV_SCALE;

  return result;
}
