/* extremewind-png.js — 8-bit grayscale PNG loader for the extreme-wind (vb,0) grid.
   Decodes data/extremewind1.png (generated by scripts/generate-extremewind-grid.js):
     - 8-bit grayscale, Sub filter (type 1) per row, IDAT = zlib-compressed
     - Encoding: pixel = round(vb0_m_s · EXTREMEWIND_SCALE)   (0 = no data / sea)
     - Decode:   vb0_m_s = pixel / EXTREMEWIND_SCALE

   Same fetch + DecompressionStream('deflate') path as elevation-png.js.
   Depends on: config.js for EXTREMEWIND_SCALE. Returns Float32Array (m/s, 0 = no data). */

async function loadExtremeWindPng(url, headers = {}) {
  const resp = await fetch(url, { headers });
  if (!resp.ok) throw new Error(`loadExtremeWindPng: HTTP ${resp.status} for ${url}`);
  const buf  = await resp.arrayBuffer();
  const view = new DataView(buf);
  const u8   = new Uint8Array(buf);

  const width  = view.getUint32(16);
  const height = view.getUint32(20);

  const idatParts = [];
  let obfuscated = false;                     // set if the PNG carries the 'obf' tEXt marker
  let pos = 33;   // 8(magic) + IHDR chunk
  while (pos + 8 <= buf.byteLength) {
    const chunkLen  = view.getUint32(pos);
    const chunkType = String.fromCharCode(u8[pos+4], u8[pos+5], u8[pos+6], u8[pos+7]);
    if (chunkType === 'IEND') break;
    if (chunkType === 'IDAT') idatParts.push(u8.slice(pos + 8, pos + 8 + chunkLen));
    else if (chunkType === 'tEXt' && u8[pos+8] === 111 && u8[pos+9] === 98 && u8[pos+10] === 102) obfuscated = true;
    pos += 4 + 4 + chunkLen + 4;
  }
  const idatLen = idatParts.reduce((s, c) => s + c.length, 0);
  const idat = new Uint8Array(idatLen);
  let off = 0; for (const p of idatParts) { idat.set(p, off); off += p.length; }

  const stream = new Blob([idat]).stream().pipeThrough(new DecompressionStream('deflate'));
  const raw    = new Uint8Array(await new Response(stream).arrayBuffer());

  const scanStride = 1 + width;
  let img = new Uint8Array(width * height);
  for (let row = 0; row < height; row++) {
    const base = row * scanStride;
    let prev = 0;
    for (let col = 0; col < width; col++) {
      const px = (raw[base + 1 + col] + prev) & 0xFF;
      prev = px;
      img[row * width + col] = px;
    }
  }

  /* Reverse the grid obfuscation (only when the PNG is marked) */
  if (obfuscated) {
    if (typeof GridObfus === 'undefined') throw new Error('loadExtremeWindPng: grid-deshuffle.js must load before an obfuscated grid');
    img = GridObfus.decode(img, width, height);
  }

  const result = new Float32Array(width * height);
  const scale = (typeof EXTREMEWIND_SCALE !== 'undefined') ? EXTREMEWIND_SCALE : 4;
  for (let i = 0; i < result.length; i++) result[i] = img[i] / scale;   // vb0 m/s; 0 = no data

  return result;
}
