/* pt-text-ro.js — Proiect Tehnic chapter prose, ROMANIAN (legally operative version).
   PT-SPEC.md D1/D3: document templates live OUTSIDE i18n (these are pages of legal text,
   not UI strings). {placeholders} are substituted by pt-doc.js; an unresolved placeholder
   renders as a red "[de completat]" and is listed in the pre-flight.
   Normative reference TITLES stay in Romanian in BOTH languages (proper names). */

window.PT_TEXT_RO = {
  common: {
    docTitle:   'MEMORIU TEHNIC',
    docSub:     'CENTRALĂ ELECTRICĂ FOTOVOLTAICĂ',
    pag:        'Pag.',
    editia:     'Ediția',
    revizia:    'Revizia',
    cod:        'Cod',
    missing:    '[de completat]',
    annexNote:  'se anexează prezentei documentații',
    legalNote:  '',   /* RO is the operative version - no note needed */
  },

  cover: {
    titlePre:  'Proiect tehnic și detalii de execuție',
    titleTpl:  '„Instalație de producere a energiei electrice din surse regenerabile - energie solară {kwp} kWp”',
    spec:      'Specialitatea: instalații electrice',
    lblObiectiv:   'Denumirea obiectivului',
    lblBeneficiar: 'Beneficiar',
    lblAdresa:     'Adresa obiectivului',
    lblProiectant: 'Proiectant de specialitate instalații electrice',
    lblFaza:       'Faza de proiectare',
    lblData:       'Data întocmirii',
  },

  borderou: {
    title: 'BORDEROU',
    cols:  ['Nr. crt.', 'Denumire document', 'Cod document', 'Pagini', 'Format'],
    memoriu: 'Memoriu tehnic',
    anexa1:  'Anexa 1 - Breviar de calcul CEF (producție estimată)',
    planse:  [
      ['Plan amplasament CEF',                'IE001', 'A0'],
      ['Schemă monofilară racord',            'IE002', 'A4'],
      ['Schemă monofilară TE-CEF',            'IE003', 'A4'],
      ['Schemă monofilară TE-CC',             'IE004', 'A4'],
      ['Plan amplasament panouri fotovoltaice','IE005', 'A1'],
    ],
  },

  semnaturi: {
    title: 'LISTA DE SEMNĂTURI',
    cols:  ['Calitate', 'Nume și prenume', 'Atestat / Legitimație', 'Semnătura'],
    rows: {
      proiectant:  'Proiectant instalații electrice',
      verificator: 'Verificator de proiecte - cerința {domeniu}',
      atestatSoc:  'Atestat societate',
    },
    note: 'Documentația produce efecte numai după semnarea de către proiectantul atestat și verificarea de către verificatorul de proiecte atestat pentru cerința Ie.',
  },

  atestate: {
    title: 'ATESTATE',
    s1: 'Atestat societate',
    s2: 'Atestat proiectant',
    body: 'Atestatul ANRE al societății proiectante ({atestatSocietate}) și atestatul proiectantului ({atestatProiectant}) se anexează prezentei documentații, în copie conformă cu originalul.',
  },

  cuprins: { title: 'CUPRINS' },

  dategen: {
    title: 'DATE GENERALE',
    s: [
      ['DENUMIREA OBIECTIVULUI DE INVESTIȚIE',
       '„Instalație de producere a energiei electrice din surse regenerabile - energie solară {kwp} kWp”, denumită în continuare CEF (centrală electrică fotovoltaică).'],
      ['AMPLASAMENTUL OBIECTIVULUI',
       '{adresaObiectiv}'],
      ['BENEFICIARUL INVESTIȚIEI',
       '{beneficiarFirma}, {beneficiarAdresa}'],
      ['FAZA DE PROIECTARE',
       '{faza}'],
      ['ELABORATORUL PROIECTULUI',
       '{proiectantFirma}, {proiectantAdresa} - proiectant de specialitate instalații electrice: {proiectantNume}, {atestatProiectant}.'],
    ],
  },

  necesitate: {
    title: 'NECESITATEA ȘI OPORTUNITATEA INVESTIȚIEI',
    s1title: 'Scurtă prezentare',
    p1: 'Sursele regenerabile de energie au o pondere din ce în ce mai mare în sistemele energetice, atât datorită politicilor de decarbonare, cât și datorită creșterii prețului energiei obținute prin metode convenționale. Energia solară este o sursă regenerabilă recunoscută oficial, disponibilă pe amplasament fără costuri de combustibil.',
    p2: 'Având în vedere necesarul de energie electrică al beneficiarului și oportunitatea de utilizare a suprafețelor disponibile în scopul producerii de energie electrică, se dorește realizarea unei instalații de producere cu puterea instalată de {kwp} kWp și utilizarea energiei produse pentru autoconsum.',
    s2title: 'Deficiențe ale situației actuale',
    p3: 'Alimentarea cu energie electrică se realizează integral din rețeaua de distribuție, cu costurile și amprenta de carbon aferente.',
    s3title: 'Impactul nerealizării investiției',
    p4: 'Nerealizarea proiectului menține cheltuielile actuale cu energia electrică și nivelul actual al emisiilor de gaze cu efect de seră.',
    s4title: 'Avantaje / impact pozitiv',
    bullets: [
      'diminuarea cheltuielilor cu energia electrică - producție anuală estimată {anualKwh} kWh;',
      'reducerea pierderilor din rețea datorită producerii energiei la locul de consum;',
      'reducerea emisiilor de gaze cu efect de seră cu aproximativ {co2} kg CO₂/an (factor de emisie ~0,265 kg CO₂/kWh, mix național - sursa: EEA/ANRE);',
      'economisirea resurselor primare fosile.',
    ],
  },

  abrevieri: {
    title: 'LISTA ABREVIERI',
    rows: [
      ['ANRE',   'Autoritatea Națională de Reglementare în Domeniul Energiei'],
      ['ATR',    'Aviz tehnic de racordare'],
      ['CC',     'Curent continuu'],
      ['CA',     'Curent alternativ'],
      ['CEF',    'Centrală electrică fotovoltaică (instalația de producere)'],
      ['CEFND',  'Centrală electrică fotovoltaică nedispecerizabilă'],
      ['MPPT',   'Urmărirea punctului de putere maximă (Maximum Power Point Tracking)'],
      ['OD',     'Operator de distribuție'],
      ['PIF',    'Punere în funcțiune'],
      ['ROCOF',  'Viteza de variație a frecvenței (Rate of Change of Frequency)'],
      ['RfG',    'Regulamentul (UE) 2016/631 - cod de rețea privind racordarea instalațiilor de generare'],
      ['SEM',    'Sistem de monitorizare și limitare a puterii (fără injecție în rețea)'],
      ['SEN',    'Sistemul electroenergetic național'],
      ['SPD',    'Dispozitiv de protecție la supratensiuni (Surge Protective Device)'],
      ['STC',    'Condiții standard de test (1000 W/m², 25 °C, AM 1.5)'],
      ['TGD',    'Tablou general de distribuție'],
      ['Un',     'Tensiunea nominală a rețelei'],
    ],
  },

  normative: {
    title: 'NORMATIVE ȘI REGLEMENTĂRI TEHNICE',
    intro: 'Soluțiile tehnice din prezenta documentație sunt în conformitate cu legislația în vigoare și îndeplinesc cerințele esențiale de calitate stabilite de următoarele acte normative și standarde (citate o singură dată aici; capitolele ulterioare fac trimitere la prezenta listă):',
    rows: [
      ['SR CLC/TS 61836:2016',  'Sisteme de conversie fotovoltaică a energiei solare. Termeni și simboluri'],
      ['SR HD 60364-7-712:2016','Instalații electrice în construcții. Partea 7-712: Sisteme de alimentare cu energie solară fotovoltaică (PV)'],
      ['SR EN IEC 62790:2020',  'Cutii de joncțiune pentru module fotovoltaice. Cerințe de securitate și încercări'],
      ['SR EN 60904',           'Dispozitive fotovoltaice'],
      ['SR EN 62109-1:2011',    'Securitatea convertoarelor de putere utilizate în rețele electrice fotovoltaice. Partea 1: Cerințe generale'],
      ['SR EN 62109-2:2012',    'Securitatea convertoarelor de putere utilizate în rețele electrice fotovoltaice. Partea 2: Cerințe particulare pentru invertoare'],
      ['SR EN 50530:2011',      'Eficiența totală a invertoarelor fotovoltaice conectate la rețea'],
      ['SR EN 60269-6:2011',    'Siguranțe fuzibile de joasă tensiune. Partea 6: Elemente de înlocuire pentru protecția sistemelor fotovoltaice (gPV)'],
      ['SR EN 61215',           'Module fotovoltaice. Calificarea proiectului și omologare'],
      ['SR EN IEC 61730',       'Calificarea modulelor fotovoltaice din punctul de vedere al securității'],
      ['SR CEI/EN 61000',       'Compatibilitate electromagnetică (CEM)'],
      ['NTE 007/08/00',         'Normativ pentru proiectarea și executarea rețelelor de cabluri electrice'],
      ['I7/2011',               'Normativ pentru proiectarea, execuția și exploatarea instalațiilor electrice aferente clădirilor'],
      ['PE 102/86',             'Normativ pentru proiectarea instalațiilor de conexiuni și distribuție cu tensiuni până la 1000 V c.a.'],
      ['PE 103/92',             'Instrucțiuni pentru dimensionarea și verificarea instalațiilor electroenergetice la solicitări mecanice și termice la scurtcircuit'],
      ['NTE 006/06/00',         'Normativ privind metodologia de calcul al curenților de scurtcircuit în rețelele electrice cu tensiunea sub 1 kV'],
      ['1 RE-Ip 30/2004',       'Îndreptar de proiectare și execuție a instalațiilor de legare la pământ'],
      ['PE 116/94',             'Normativ de încercări și măsurători la echipamente și instalații electrice'],
      ['CR 1-1-3/2012',         'Cod de proiectare. Evaluarea acțiunii zăpezii asupra construcțiilor'],
      ['CR 1-1-4/2012',         'Cod de proiectare. Evaluarea acțiunii vântului asupra construcțiilor'],
      ['Ordin ANRE 208/2018',   'Normă tehnică privind cerințele tehnice de racordare la rețelele electrice de interes public pentru module generatoare'],
      ['Ordin ANRE 228/2018',   'Condiții tehnice de racordare la rețelele electrice de interes public pentru prosumatori'],
      ['Ordin ANRE 51/2019',    'Procedura de notificare pentru racordarea unităților generatoare și de verificare a conformității'],
      ['Legea 10/1995 (r)',     'Privind calitatea în construcții, cu reglementările de aplicare'],
      ['Legea 50/1991 (r)',     'Privind autorizarea executării lucrărilor de construcții'],
      ['HG 907/2016',           'Privind etapele de elaborare și conținutul-cadru al documentațiilor tehnico-economice aferente investițiilor finanțate din fonduri publice'],
      ['Legea 307/2006',        'Privind apărarea împotriva incendiilor + Ordin MAI 163/2007 (norme generale)'],
      ['HGR 766/1997',          'Regulamente privind calitatea în construcții; stabilirea categoriei de importanță'],
    ],
  },

  prezentare: {
    title: 'PREZENTAREA PROIECTULUI',
    p1: 'Beneficiarul dorește realizarea unei instalații de producere a energiei electrice (CEF) cu puterea instalată de {kwp} kWp ({nrModule} module fotovoltaice), amplasată la {adresaObiectiv}.',
    p2: 'Categoria de importanță a construcției, conform HGR 766/1997 și Ordinului MLPAT nr. 31/N/1997, este „{categoria}” - construcții de importanță {categoriaNume}.',
    p3noinj: 'CEF se va racorda la nivelul de tensiune de {tensiune} kV în {tablou}. Centrala va fi comandată de un sistem automat de monitorizare și limitare (SEM) care va limita puterea produsă astfel încât CEF să nu injecteze energie în rețeaua Operatorului de Distribuție. Locația va funcționa în regim de prosumator „fără injecție în rețea”.',
    p3inj: 'CEF se va racorda la nivelul de tensiune de {tensiune} kV în {tablou}. Locația va funcționa în regim de prosumator cu injecție de putere activă în rețea, conform Ordinului ANRE 228/2018; energia excedentară va fi livrată în rețeaua Operatorului de Distribuție.',
    p4: 'În cadrul proiectului sunt tratate instalațiile electrice de joasă tensiune de curent continuu (CC) și de curent alternativ (CA) aferente CEF.',
    sIntrare: 'DATE TEHNICE DE INTRARE',
    sAmplasament: 'AMPLASAMENT ȘI DATE CLIMATICE',
    pAmpl: 'Amplasament: latitudine {lat}°, longitudine {lon}°, altitudine {alt} m. Date climatice de calcul: temperatura minimă a aerului {tamin} °C, temperatura maximă {tamax} °C (valori de dimensionare folosite la calculul șirurilor - cap. Breviar de calcul).',
    sIradiere: 'DATE NIVEL IRADIERE',
    pIrad: 'Producția specifică estimată a sistemului este de {specYield} kWh/kWp/an, rezultând o producție anuală estimată de {anualKwh} kWh (metodologia de calcul și comparația cu PVGIS sunt detaliate în Anexa 1).',
    sConsum: 'DATE PRIVIND SITUAȚIA ENERGETICĂ',
    pConsum: 'Consumul anual de energie electrică al locului de consum este de {consumAnual} kWh.',
    sRacordare: 'SOLUȚIA PROPUSĂ PENTRU RACORDAREA INSTALAȚIEI',
    pRacordare: '{ptAlimentare}',
    sCEF: 'DATE TEHNICE CEF',
    pCEF: 'Centrala electrică fotovoltaică (CEF) este compusă din:',
    cefList: [
      'module fotovoltaice {modulNume}, Pi = {modulPmax} Wp - {nrModule} buc;',
      'invertor {invNume} - {nrInv} buc;',
      'tablou de curent alternativ TE-CEF 0,4 kV cu protecții - 1 buc;',
      'tablou de curent continuu TE-CC cu protecții - 1 buc;',
      '{semItem}',
      'circuite electrice de curent continuu (CC) și de curent alternativ (CA);',
      'sistem de fixare a modulelor fotovoltaice.',
    ],
    semNoinj: 'sistem automat de monitorizare și limitare a puterii (SEM), care nu permite injecția de energie în rețea - 1 buc;',
    semInj:   'sistem de măsurare bidirecțională a energiei conform reglementărilor OD;',
    sStrings: 'CONFIGURAȚIA ȘIRURILOR (STRINGURI)',
    pStrings: 'Modulele fotovoltaice se conectează în serie în șiruri (stringuri), astfel încât tensiunea maximă de circuit deschis a fiecărui șir, calculată la temperatura minimă de dimensionare, să nu depășească tensiunea maximă de intrare a invertorului. Rezultă configurația:',
    strCols: ['Șir', 'Modul', 'Module/șir (Ns×Np)', 'P șir [Wp]', 'Imp [A]', 'Ump [V]', 'Isc [A]', 'Voc,rece [V]', 'β/γ [°]'],
  },

  teste: {
    title: 'TESTE, VERIFICĂRI, MĂSURĂRI ȘI PIF',
    intro: 'Înainte de punerea în funcțiune se efectuează cel puțin următoarele verificări și măsurători (PE 116/94, SR HD 60364-6):',
    bullets: [
      'verificarea vizuală: starea generală a modulelor, cablurilor, cutiilor de joncțiune, invertorului și a instalației de legare la pământ; poziția modulelor (azimut, înclinare, umbriri), integritatea și fixarea structurii metalice;',
      'măsurarea rezistenței de izolație a circuitelor CC și CA;',
      'măsurarea continuității conductorului de protecție PE până la TGD;',
      'măsurarea rezistenței de dispersie a prizei de pământ;',
      'verificarea polarității șirurilor și măsurarea tensiunii de circuit deschis Voc și a curentului de scurtcircuit Isc pentru fiecare șir, cu compararea valorilor cu cele teoretice;',
      'măsurarea cuplului de strângere al șuruburilor structurii și modulelor (prin sondaj);',
      'probe funcționale ale invertorului și ale protecțiilor (inclusiv funcția de limitare la zero a injecției, dacă este cazul);',
      'verificarea setărilor protecțiilor de interfață conform avizului tehnic de racordare.',
    ],
  },

  faze: {
    title: 'PROGRAMUL DE URMĂRIRE A EXECUȚIEI ȘI FAZELE DETERMINANTE',
    intro: 'În conformitate cu Legea 10/1995 (actualizată), Regulamentul privind controlul de stat al calității în construcții (HG 272/1994) și normativele tehnice în vigoare, se stabilește următorul program de control al lucrărilor. Legendă: RI - registru/raport de încercări; PV - proces-verbal; PVR - proces-verbal de recepție; E - executant; B - beneficiar; P - proiectant.',
    cols: ['Nr.', 'Lucrări ce se controlează, se verifică sau se recepționează', 'Document', 'Semnează'],
    rows: [
      ['Măsurarea rezistenței de dispersie a prizei de pământ', 'RI',  'E, B'],
      ['Măsurarea continuității PE la TGD',                     'RI',  'E, B'],
      ['Verificarea calității lucrărilor ce devin ascunse',     'PV',  'E, B, P'],
      ['Verificări și încercări tablouri electrice',            'RI',  'E, B'],
      ['Montaj structură și module fotovoltaice',               'PV',  'E, B'],
      ['Montaj la poziție echipamente electrice',               'PV',  'E, B'],
      ['Verificare racordări cabluri de forță și comandă',      'PV',  'E, B'],
      ['Probe funcționale',                                     'PV',  'E, B'],
      ['Recepție la terminarea lucrărilor',                     'PVR', 'E, B, P'],
    ],
    note: 'Termenele controalelor se stabilesc de comun acord între beneficiar și executant și se comunică în timp util proiectantului pentru fazele la care prezența acestuia este obligatorie.',
  },

  anexa1: {
    title: 'ANEXA 1 - BREVIAR DE CALCUL CEF (PRODUCȚIE ESTIMATĂ)',
    introModel: 'Producția de energie a CEF a fost estimată cu instrumentul propriu de calcul (modele documentate: Hofierka/Suri 2002 - cer senin, transpoziție anisotropică PVGIS-nativă, derating termic pe suprafața de eficiență Huld 2010, pierderi unghiulare Martin-Ruiz; acuratețe documentată față de PVGIS). Unde este disponibil, se prezintă și comparația cu datele oficiale PVGIS (SARAH) importate per șir.',
    introOfficial: 'Producția de energie a CEF provine din DATELE OFICIALE PVGIS (Comisia Europeană / JRC, baza {dbinfo}), importate per șir din raportul PVGIS al fiecărei orientări. Valorile lunare și anuale prezentate mai jos sunt cele oficiale PVGIS.',
    introMixed: 'Pentru șirurile {offList}, producția provine din DATELE OFICIALE PVGIS (Comisia Europeană / JRC, baza {dbinfo}), importate per șir. Pentru celelalte șiruri ({modList}), producția a fost estimată cu instrumentul propriu de calcul (modele documentate: Hofierka/Suri 2002 - cer senin, transpoziție anisotropică PVGIS-nativă, derating termic pe suprafața de eficiență Huld 2010, pierderi unghiulare Martin-Ruiz; acuratețe documentată față de PVGIS).',
    mProd:   'Producție anuală estimată',
    mKwp:    'Putere instalată',
    mSpec:   'Producție specifică',
    mAvg:    'Medie lunară',
    cProd:   'Producția lunară de energie [kWh]',
    cDaily:  'Curbă zilnică de producție (cer senin)',
    cCvsP:   'Producție vs. consum lunar [kWh]',
    cTable:  'Tabel date lunare',
    tCols:   ['Luna', 'Energie [kWh]', 'Consum [kWh]', 'Relativ'],
    tAnual:  'Anual',
    bdTitle: 'Defalcare pe șiruri',
    bdCols:  ['Șir', 'Modul', 'Module', 'kWp', 'Încl./Az. [°]', 'PR', 'kWh/an', 'kWh/kWp'],
    pvgisTag:'date PVGIS (oficial)',
  },

  planse: {
    title: 'PLANȘE',
    note: 'Planșele de mai jos fac parte din documentație și se anexează (elaborate CAD, conform borderoului). Cartușul fiecărei planșe va conține datele de identificare de mai jos.',
    cartus: { desenat: 'Desenat', proiectat: 'Proiectat', aprobat: 'Aprobat', faza: 'Faza', scara: 'Scara', plansa: 'Planșa' },
    seAnexeaza: 'SE ANEXEAZĂ - planșă elaborată separat',
    schemaMissing: 'Schema monofilară nu poate fi generată - completați șirurile, modulele și invertorul în pașii anteriori.',
  },
};
