/* pt-text-ro.js — Proiect Tehnic chapter prose, ROMANIAN (legally operative version).
   PT-SPEC.md D1/D3: document templates live OUTSIDE i18n (these are pages of legal text,
   not UI strings). {placeholders} are substituted by pt-doc.js; an unresolved placeholder
   renders as a red "[de completat]" and is listed in the pre-flight.
   Normative reference TITLES stay in Romanian in BOTH languages (proper names). */

window.PT_TEXT_RO = {
  common: {
    docTitle:   'MEMORIU TEHNIC',
    docSub:     'CENTRALĂ ELECTRICĂ FOTOVOLTAICĂ',
    pag:        'Pag.',
    editia:     'Ediția',
    revizia:    'Revizia',
    cod:        'Cod',
    missing:    '[de completat]',
    annexNote:  'se anexează prezentei documentații',
    legalNote:  '',   /* RO is the operative version - no note needed */
  },

  cover: {
    titlePre:  'Proiect tehnic și detalii de execuție',
    titleTpl:  '„Instalație de producere a energiei electrice din surse regenerabile - energie solară {kwp} kWp”',
    spec:      'Specialitatea: instalații electrice',
    lblObiectiv:   'Denumirea obiectivului',
    lblBeneficiar: 'Beneficiar',
    lblAdresa:     'Adresa obiectivului',
    lblProiectant: 'Proiectant de specialitate instalații electrice',
    lblFaza:       'Faza de proiectare',
    lblData:       'Data întocmirii',
  },

  borderou: {
    title: 'BORDEROU',
    cols:  ['Nr. crt.', 'Denumire document', 'Cod document', 'Pagini', 'Format'],
    memoriu: 'Memoriu tehnic',
    anexa1:  'Anexa 1 - Breviar de calcul CEF (producție estimată)',
    planse:  [
      ['Plan amplasament CEF',                'IE001', 'A0'],
      ['Schemă monofilară racord',            'IE002', 'A4'],
      ['Schemă monofilară TE-CEF',            'IE003', 'A4'],
      ['Schemă monofilară TE-CC',             'IE004', 'A4'],
      ['Plan amplasament panouri fotovoltaice','IE005', 'A1'],
    ],
  },

  semnaturi: {
    title: 'LISTA DE SEMNĂTURI',
    cols:  ['Calitate', 'Nume și prenume', 'Atestat / Legitimație', 'Semnătura'],
    rows: {
      proiectant:  'Proiectant instalații electrice',
      verificator: 'Verificator de proiecte - cerința {domeniu}',
      atestatSoc:  'Atestat societate',
    },
    note: 'Documentația produce efecte numai după semnarea de către proiectantul atestat și verificarea de către verificatorul de proiecte atestat pentru cerința Ie.',
  },

  atestate: {
    title: 'ATESTATE',
    s1: 'Atestat societate',
    s2: 'Atestat proiectant',
    body: 'Atestatul ANRE al societății proiectante ({atestatSocietate}) și atestatul proiectantului ({atestatProiectant}) se anexează prezentei documentații, în copie conformă cu originalul.',
  },

  cuprins: { title: 'CUPRINS' },

  dategen: {
    title: 'DATE GENERALE',
    s: [
      ['DENUMIREA OBIECTIVULUI DE INVESTIȚIE',
       '„Instalație de producere a energiei electrice din surse regenerabile - energie solară {kwp} kWp”, denumită în continuare CEF (centrală electrică fotovoltaică).'],
      ['AMPLASAMENTUL OBIECTIVULUI',
       '{adresaObiectiv}'],
      ['BENEFICIARUL INVESTIȚIEI',
       '{beneficiarFirma}, {beneficiarAdresa}'],
      ['FAZA DE PROIECTARE',
       '{faza}'],
      ['ELABORATORUL PROIECTULUI',
       '{proiectantFirma}, {proiectantAdresa} - proiectant de specialitate instalații electrice: {proiectantNume}, {atestatProiectant}.'],
    ],
  },

  necesitate: {
    title: 'NECESITATEA ȘI OPORTUNITATEA INVESTIȚIEI',
    s1title: 'Scurtă prezentare',
    p1: 'Sursele regenerabile de energie au o pondere din ce în ce mai mare în sistemele energetice, atât datorită politicilor de decarbonare, cât și datorită creșterii prețului energiei obținute prin metode convenționale. Energia solară este o sursă regenerabilă recunoscută oficial, disponibilă pe amplasament fără costuri de combustibil.',
    p2: 'Având în vedere necesarul de energie electrică al beneficiarului și oportunitatea de utilizare a suprafețelor disponibile în scopul producerii de energie electrică, se dorește realizarea unei instalații de producere cu puterea instalată de {kwp} kWp și utilizarea energiei produse pentru autoconsum.',
    s2title: 'Deficiențe ale situației actuale',
    p3: 'Alimentarea cu energie electrică se realizează integral din rețeaua de distribuție, cu costurile și amprenta de carbon aferente.',
    s3title: 'Impactul nerealizării investiției',
    p4: 'Nerealizarea proiectului menține cheltuielile actuale cu energia electrică și nivelul actual al emisiilor de gaze cu efect de seră.',
    s4title: 'Avantaje / impact pozitiv',
    bullets: [
      'diminuarea cheltuielilor cu energia electrică - producție anuală estimată {anualKwh} kWh;',
      'reducerea pierderilor din rețea datorită producerii energiei la locul de consum;',
      'reducerea emisiilor de gaze cu efect de seră cu aproximativ {co2} kg CO₂/an (factor de emisie ~0,265 kg CO₂/kWh, mix național - sursa: EEA/ANRE);',
      'economisirea resurselor primare fosile.',
    ],
  },

  abrevieri: {
    title: 'LISTA ABREVIERI',
    rows: [
      ['ANRE',   'Autoritatea Națională de Reglementare în Domeniul Energiei'],
      ['ATR',    'Aviz tehnic de racordare'],
      ['CC',     'Curent continuu'],
      ['CA',     'Curent alternativ'],
      ['CEF',    'Centrală electrică fotovoltaică (instalația de producere)'],
      ['CEFND',  'Centrală electrică fotovoltaică nedispecerizabilă'],
      ['MPPT',   'Urmărirea punctului de putere maximă (Maximum Power Point Tracking)'],
      ['OD',     'Operator de distribuție'],
      ['PIF',    'Punere în funcțiune'],
      ['ROCOF',  'Viteza de variație a frecvenței (Rate of Change of Frequency)'],
      ['RfG',    'Regulamentul (UE) 2016/631 - cod de rețea privind racordarea instalațiilor de generare'],
      ['SEM',    'Sistem de monitorizare și limitare a puterii (fără injecție în rețea)'],
      ['SEN',    'Sistemul electroenergetic național'],
      ['SPD',    'Dispozitiv de protecție la supratensiuni (Surge Protective Device)'],
      ['STC',    'Condiții standard de test (1000 W/m², 25 °C, AM 1.5)'],
      ['TGD',    'Tablou general de distribuție'],
      ['Un',     'Tensiunea nominală a rețelei'],
    ],
  },

  normative: {
    title: 'NORMATIVE ȘI REGLEMENTĂRI TEHNICE',
    intro: 'Soluțiile tehnice din prezenta documentație sunt în conformitate cu legislația în vigoare și îndeplinesc cerințele esențiale de calitate stabilite de următoarele acte normative și standarde (citate o singură dată aici; capitolele ulterioare fac trimitere la prezenta listă):',
    rows: [
      ['SR CLC/TS 61836:2016',  'Sisteme de conversie fotovoltaică a energiei solare. Termeni și simboluri'],
      ['SR HD 60364-7-712:2016','Instalații electrice în construcții. Partea 7-712: Sisteme de alimentare cu energie solară fotovoltaică (PV)'],
      ['SR EN IEC 62790:2020',  'Cutii de joncțiune pentru module fotovoltaice. Cerințe de securitate și încercări'],
      ['SR EN 60904',           'Dispozitive fotovoltaice'],
      ['SR EN 62109-1:2011',    'Securitatea convertoarelor de putere utilizate în rețele electrice fotovoltaice. Partea 1: Cerințe generale'],
      ['SR EN 62109-2:2012',    'Securitatea convertoarelor de putere utilizate în rețele electrice fotovoltaice. Partea 2: Cerințe particulare pentru invertoare'],
      ['SR EN 50530:2011',      'Eficiența totală a invertoarelor fotovoltaice conectate la rețea'],
      ['SR EN 60269-6:2011',    'Siguranțe fuzibile de joasă tensiune. Partea 6: Elemente de înlocuire pentru protecția sistemelor fotovoltaice (gPV)'],
      ['SR EN 61215',           'Module fotovoltaice. Calificarea proiectului și omologare'],
      ['SR EN IEC 61730',       'Calificarea modulelor fotovoltaice din punctul de vedere al securității'],
      ['SR CEI/EN 61000',       'Compatibilitate electromagnetică (CEM)'],
      ['NTE 007/08/00',         'Normativ pentru proiectarea și executarea rețelelor de cabluri electrice'],
      ['I7/2011',               'Normativ pentru proiectarea, execuția și exploatarea instalațiilor electrice aferente clădirilor'],
      ['PE 102/86',             'Normativ pentru proiectarea instalațiilor de conexiuni și distribuție cu tensiuni până la 1000 V c.a.'],
      ['PE 103/92',             'Instrucțiuni pentru dimensionarea și verificarea instalațiilor electroenergetice la solicitări mecanice și termice la scurtcircuit'],
      ['NTE 006/06/00',         'Normativ privind metodologia de calcul al curenților de scurtcircuit în rețelele electrice cu tensiunea sub 1 kV'],
      ['1 RE-Ip 30/2004',       'Îndreptar de proiectare și execuție a instalațiilor de legare la pământ'],
      ['PE 116/94',             'Normativ de încercări și măsurători la echipamente și instalații electrice'],
      ['CR 1-1-3/2012',         'Cod de proiectare. Evaluarea acțiunii zăpezii asupra construcțiilor'],
      ['CR 1-1-4/2012',         'Cod de proiectare. Evaluarea acțiunii vântului asupra construcțiilor'],
      ['Ordin ANRE 208/2018',   'Normă tehnică privind cerințele tehnice de racordare la rețelele electrice de interes public pentru module generatoare'],
      ['Ordin ANRE 228/2018',   'Condiții tehnice de racordare la rețelele electrice de interes public pentru prosumatori'],
      ['Ordin ANRE 51/2019',    'Procedura de notificare pentru racordarea unităților generatoare și de verificare a conformității'],
      ['Legea 10/1995 (r)',     'Privind calitatea în construcții, cu reglementările de aplicare'],
      ['Legea 50/1991 (r)',     'Privind autorizarea executării lucrărilor de construcții'],
      ['HG 907/2016',           'Privind etapele de elaborare și conținutul-cadru al documentațiilor tehnico-economice aferente investițiilor finanțate din fonduri publice'],
      ['Legea 307/2006',        'Privind apărarea împotriva incendiilor + Ordin MAI 163/2007 (norme generale)'],
      ['HGR 766/1997',          'Regulamente privind calitatea în construcții; stabilirea categoriei de importanță'],
    ],
  },

  prezentare: {
    title: 'PREZENTAREA PROIECTULUI',
    p1: 'Beneficiarul dorește realizarea unei instalații de producere a energiei electrice (CEF) cu puterea instalată de {kwp} kWp ({nrModule} module fotovoltaice), amplasată la {adresaObiectiv}.',
    p2: 'Categoria de importanță a construcției, conform HGR 766/1997 și Ordinului MLPAT nr. 31/N/1997, este „{categoria}” - construcții de importanță {categoriaNume}.',
    p3noinj: 'CEF se va racorda la nivelul de tensiune de {tensiune} kV în {tablou}. Centrala va fi comandată de un sistem automat de monitorizare și limitare (SEM) care va limita puterea produsă astfel încât CEF să nu injecteze energie în rețeaua Operatorului de Distribuție. Locația va funcționa în regim de prosumator „fără injecție în rețea”.',
    p3inj: 'CEF se va racorda la nivelul de tensiune de {tensiune} kV în {tablou}. Locația va funcționa în regim de prosumator cu injecție de putere activă în rețea, conform Ordinului ANRE 228/2018; energia excedentară va fi livrată în rețeaua Operatorului de Distribuție.',
    p4: 'În cadrul proiectului sunt tratate instalațiile electrice de joasă tensiune de curent continuu (CC) și de curent alternativ (CA) aferente CEF.',
    sIntrare: 'DATE TEHNICE DE INTRARE',
    intrareCols: ['Parametru', 'Valoare'],
    intrareRows: [
      ['Puterea instalată (în module fotovoltaice)', '{kwp} kWp'],
      ['Puterea instalată (în invertoare)',          '{pinvKw} kW'],
      ['Tensiunea de lucru',                         'Un = {unV} V'],
      ['Frecvența de utilizare',                     'f = 50 Hz'],
      ['Factorul de putere',                         'cos φ > 0,99'],
    ],
    pSuprafata: 'Centrala electrică fotovoltaică va ocupa o suprafață de circa {suprafata} m², având dispunerea panourilor pe direcția {orientare}.',
    pBransament: 'Branșamentul necesar obiectivului nu face obiectul prezentei documentații.',
    sAmplasament: 'AMPLASAMENT ȘI DATE CLIMATICE',
    pAmpl: 'Amplasament: latitudine {lat}°, longitudine {lon}°, altitudine {alt} m. Date climatice de calcul: temperatura minimă a aerului {tamin} °C, temperatura maximă {tamax} °C (valori de dimensionare folosite la calculul șirurilor - cap. Breviar de calcul).',
    sIradiere: 'DATE NIVEL IRADIERE',
    pIrad: 'Producția specifică estimată a sistemului este de {specYield} kWh/kWp/an, rezultând o producție anuală estimată de {anualKwh} kWh (metodologia de calcul și comparația cu PVGIS sunt detaliate în Anexa 1).',
    sConsum: 'DATE PRIVIND SITUAȚIA ENERGETICĂ',
    pConsum: 'Consumul anual de energie electrică al locului de consum este de {consumAnual} kWh.',
    sRacordare: 'SOLUȚIA PROPUSĂ PENTRU RACORDAREA INSTALAȚIEI',
    pRacordare: '{ptAlimentare}',
    pRacord1: 'Tabloul electric de racord al instalației fotovoltaice (TE-CEF) se va conecta la nivelul de tensiune de {tensiune} kV în {tablou}. Racordul se realizează în cablu {matACNume}, dimensionat din condiția de cădere de tensiune și de încărcare termică, cu lungimea de {lenAC} m.',
    racordCols: ['Circuit', 'P c.a. [kW]', 'I c.a. [A]', 'Secțiune [mm²]', 'Disjunctor [A]', 'ΔU [%]'],
    pRacord2: 'Fiecare invertor se racordează pe circuit propriu, protejat cu disjunctor automat; circuitele converg într-o protecție diferențială comună, conform capitolului de protecții. Secțiunile și curenții nominali de mai sus rezultă din breviarul de calcul (relațiile de dimensionare a cablurilor c.a.).',
    pRacordNoinj: 'Instalația va fi prevăzută cu un sistem de monitorizare și limitare a puterii active (releu de monitorizare a tensiunii și analizor de energie), care transmite invertoarelor informații despre parametrii rețelei și reglează puterea de ieșire în funcție de consumul instantaneu, astfel încât CEF să nu injecteze energie în rețeaua Operatorului de Distribuție.',
    pRacordPlansa: 'Soluția propusă pentru racordarea CEF este detaliată în planșa IE002 - Schemă monofilară racord.',
    matCu: 'de cupru (Cu)',
    matAl: 'de aluminiu (Al)',
    sCEF: 'DATE TEHNICE CEF',
    pCEF: 'Centrala electrică fotovoltaică (CEF) este compusă din:',
    cefList: [
      'module fotovoltaice {modulNume}, Pi = {modulPmax} Wp - {nrModule} buc;',
      'invertor {invNume} - {nrInv} buc;',
      'tablou de curent alternativ TE-CEF 0,4 kV cu protecții - 1 buc;',
      'tablou de curent continuu TE-CC cu protecții - 1 buc;',
      '{semItem}',
      'circuite electrice de curent continuu (CC) și de curent alternativ (CA);',
      'sistem de fixare a modulelor fotovoltaice.',
    ],
    semNoinj: 'sistem automat de monitorizare și limitare a puterii (SEM), care nu permite injecția de energie în rețea - 1 buc;',
    semInj:   'sistem de măsurare bidirecțională a energiei conform reglementărilor OD;',
    sInvertor: 'CARACTERISTICI TEHNICE INVERTOARE',
    pInvertor: 'Invertoarele preiau energia în curent continuu de la modulele fotovoltaice, în intervalele de variație a tensiunii și a curentului, și livrează la ieșire tensiune alternativă, cu respectarea condițiilor tehnice impuse de operatorul de distribuție. Caracteristicile tehnice ale invertoarelor prevăzute sunt:',
    invCols: ['Parametru', 'U.M.'],
    invValCol: 'Valoare',
    invRows: [
      ['Putere nominală c.a.',                'kW',  'pac'],
      ['Tensiunea maximă de intrare c.c.',    'V',   'vinvmax'],
      ['Număr MPPT / invertor',               'Nr.', 'nmppt'],
      ['Plaja de tensiune MPPT',              'V',   'vmppt'],
      ['Curent maxim de intrare / MPPT',      'A',   'impptmax'],
      ['Curent maxim de scurtcircuit / MPPT', 'A',   'iscmppt'],
    ],
    sStrings: 'CONFIGURAȚIA ȘIRURILOR (STRINGURI)',
    pStrings: 'Modulele fotovoltaice se conectează în serie în șiruri (stringuri), astfel încât tensiunea maximă de circuit deschis a fiecărui șir, calculată la temperatura minimă de dimensionare, să nu depășească tensiunea maximă de intrare a invertorului. Rezultă configurația:',
    strCols: ['Șir', 'Modul', 'Module/șir (Ns×Np)', 'P șir [Wp]', 'Imp [A]', 'Ump [V]', 'Isc [A]', 'Voc,rece [V]', 'β/γ [°]'],
  },

  protectii: {
    title: 'PROTECȚII ȘI APARATAJ DE COMUTAȚIE',
    intro: 'Alegerea și verificarea aparatajului de comutație și protecție s-a făcut separat pe partea de curent continuu și pe cea de curent alternativ, conform I7/2011 și SR EN IEC 62548, respectiv relației de dimensionare a siguranțelor de șir din metodologia de proiectare.',
    dcTitle: 'Partea de curent continuu (c.c.)',
    dcRule: 'Siguranța fuzibilă de șir (gPV) se alege în fereastra: max(Isc ; 1,25·Imp) ≤ Inf ≤ min(2·Isc ; Iprod,FV ; Iprod,inv), unde Iprod,FV este curentul maxim al siguranței în serie din fișa tehnică a modulului, iar Iprod,inv cel din fișa invertorului. Limita superioară efectivă este cea mai mică dintre valorile disponibile.',
    dcCols: ['Șir', 'Isc [A]', '1,25·Imp [A]', 'Inf,min [A]', 'Inf,max [A]', 'gPV ales [A]', 'Necesară', 'Verificare'],
    dcReq: 'da', dcOpt: 'opțional',
    dcNoteUn: 'Tensiunea nominală a siguranțelor și a separatorului de sarcină c.c.: Un ≥ {vmax} V (tensiunea maximă de intrare c.c. a invertorului).',
    dcNoteSpd: 'Descărcător de supratensiuni c.c. tip 2: Uc = {ucdc} V (≥ tensiunea maximă c.c. a invertorului), In ≥ 10 kA (8/20 µs), Up cât mai redus. Se prevede câte un descărcător pe fiecare șir.',
    dcNoteSep: 'Pe intrarea de c.c. a invertorului se prevede un separator/întrerupător manual de sarcină, cu Un ≥ {vmax} V.',
    dcSingle: 'La șirurile unice pe o intrare MPPT curentul invers de defect nu poate apărea, deci siguranța de șir nu este obligatorie; ea devine necesară la două sau mai multe șiruri conectate în paralel. Descărcătorul c.c. rămâne recomandat în toate cazurile.',
    acTitle: 'Partea de curent alternativ (c.a.)',
    acCols: ['Circuit', 'I inv,ca [A]', 'Disjunctor In [A]', 'Verificare'],
    acRule: 'Disjunctorul fiecărui circuit se alege cu In ≥ I inv,ca, curentul nominal al invertorului calculat la cosφ = 1.',
    acNoteRcd: 'Protecție diferențială: RCD tip A; se prevede RCD tip B dacă invertorul nu asigură monitorizarea curentului rezidual de componentă continuă.',
    acNoteSpd: 'Descărcător de supratensiuni c.a. tip 2, cu Uc ≥ 1,1·Un și In ≥ max(10 kA ; Icc la punctul de racord); obligatoriu dacă distanța până la blocul de măsură și protecție depășește 10 m.',
    acNoteIcc: 'Capacitatea de rupere a disjunctoarelor de c.a.: Icn ≥ Icc la punctul de racord = {icc} kA. Se verifică suplimentar stabilitatea termică și electrodinamică a aparatajului.',
    ok: 'se verifică', bad: 'NU se verifică',
  },

  economic: {
    title: 'ANALIZĂ ECONOMICĂ',
    intro: 'Analiza economică s-a realizat pornind de la costul total al investiției și de la beneficiul anual obținut prin valorificarea energiei produse: energia autoconsumată este evaluată la prețul de furnizare e1, iar surplusul injectat în rețea la prețul e2. Se prezintă comparativ sistemul proiectat și sistemul de referință „optim” (module orientate spre sud, la înclinarea optimă), pe un orizont de analiză de {n} ani, la o rată de actualizare de {rate} %.',
    cols: ['Indicator', 'U.M.', 'Sistem proiectat', 'Sistem optim'],
    rows: {
      prod:  'Producție anuală de energie',
      eauto: 'Energie autoconsumată',
      einj:  'Energie injectată în rețea',
      scr:   'Rata de autoconsum',
      b:     'Beneficiu anual (B)',
      inv:   'Valoarea investiției (C_FV)',
      tr:    'Termen de recuperare (Tr)',
      rir:   'Rata internă de rentabilitate (RIR)',
      vna:   'Valoarea netă actualizată (VNA)',
    },
    umKwh: 'kWh/an', umPct: '%', umAni: 'ani',
    verdictOk: 'Concluzie: rata internă de rentabilitate a sistemului proiectat ({rir} %) este superioară ratei de actualizare considerate ({rate} %), iar valoarea netă actualizată este pozitivă ({vna}). Investiția este eficientă economic pe orizontul de analiză de {n} ani.',
    verdictBad: 'Concluzie: la parametrii considerați, rata internă de rentabilitate a sistemului proiectat ({rir} %) nu depășește rata de actualizare ({rate} %). Eficiența economică a investiției depinde de evoluția prețului energiei și de eventualele finanțări nerambursabile.',
    note: 'Valorile de mai sus rezultă din datele introduse la pasul de analiză economică (prețuri, cost, orizont, rată). Durata de viață a invertorului fiind de circa 10 ani, pentru orizonturi de analiză mai mari costul acestuia se consideră de două ori.',
  },

  teste: {
    title: 'TESTE, VERIFICĂRI, MĂSURĂRI ȘI PIF',
    intro: 'Înainte de punerea în funcțiune se efectuează cel puțin următoarele verificări și măsurători (PE 116/94, SR HD 60364-6):',
    bullets: [
      'verificarea vizuală: starea generală a modulelor, cablurilor, cutiilor de joncțiune, invertorului și a instalației de legare la pământ; poziția modulelor (azimut, înclinare, umbriri), integritatea și fixarea structurii metalice;',
      'măsurarea rezistenței de izolație a circuitelor CC și CA;',
      'măsurarea continuității conductorului de protecție PE până la TGD;',
      'măsurarea rezistenței de dispersie a prizei de pământ;',
      'verificarea polarității șirurilor și măsurarea tensiunii de circuit deschis Voc și a curentului de scurtcircuit Isc pentru fiecare șir, cu compararea valorilor cu cele teoretice;',
      'măsurarea cuplului de strângere al șuruburilor structurii și modulelor (prin sondaj);',
      'probe funcționale ale invertorului și ale protecțiilor (inclusiv funcția de limitare la zero a injecției, dacă este cazul);',
      'verificarea setărilor protecțiilor de interfață conform avizului tehnic de racordare.',
    ],
  },

  faze: {
    title: 'PROGRAMUL DE URMĂRIRE A EXECUȚIEI ȘI FAZELE DETERMINANTE',
    intro: 'În conformitate cu Legea 10/1995 (actualizată), Regulamentul privind controlul de stat al calității în construcții (HG 272/1994) și normativele tehnice în vigoare, se stabilește următorul program de control al lucrărilor. Legendă: RI - registru/raport de încercări; PV - proces-verbal; PVR - proces-verbal de recepție; E - executant; B - beneficiar; P - proiectant.',
    cols: ['Nr.', 'Lucrări ce se controlează, se verifică sau se recepționează', 'Document', 'Semnează'],
    rows: [
      ['Măsurarea rezistenței de dispersie a prizei de pământ', 'RI',  'E, B'],
      ['Măsurarea continuității PE la TGD',                     'RI',  'E, B'],
      ['Verificarea calității lucrărilor ce devin ascunse',     'PV',  'E, B, P'],
      ['Verificări și încercări tablouri electrice',            'RI',  'E, B'],
      ['Montaj structură și module fotovoltaice',               'PV',  'E, B'],
      ['Montaj la poziție echipamente electrice',               'PV',  'E, B'],
      ['Verificare racordări cabluri de forță și comandă',      'PV',  'E, B'],
      ['Probe funcționale',                                     'PV',  'E, B'],
      ['Recepție la terminarea lucrărilor',                     'PVR', 'E, B, P'],
    ],
    note: 'Termenele controalelor se stabilesc de comun acord între beneficiar și executant și se comunică în timp util proiectantului pentru fazele la care prezența acestuia este obligatorie.',
  },

  boq: {
    title: 'LISTA DE CANTITĂȚI',
    intro: 'Cantitățile de mai jos sunt estimate automat pe baza configurației proiectului (module, invertoare, cablaje). Ele reprezintă o listă orientativă de materiale și echipamente; proiectantul le verifică și le completează cu lucrările civile și cu materialele mărunte, în funcție de situația din teren.',
    cols: ['Nr.', 'Denumire produs / lucrare', 'U.M.', 'Cant.'],
    sec: {
      echip: 'Echipamente principale',
      elec: 'Instalații electrice și cablaje',
      tabl: 'Echipare tablouri și protecții',
      civ: 'Lucrări civile și diverse',
    },
    it: {
      struct: 'Structură de montaj (șine, cleme de capăt/mijloc, prinderi)',
      dcRed: 'Cablu solar c.c. H1Z2Z2-K (roșu, +)',
      dcBlack: 'Cablu solar c.c. H1Z2Z2-K (negru, -)',
      ac: 'Cablu de alimentare c.a.',
      mc4: 'Conectori fotovoltaici tip MC4 (perechi + rezerve)',
      ground: 'Priză de pământ - electrozi + platbandă OlZn 40x4 + accesorii',
      fuse: 'Siguranță fuzibilă gPV pentru string',
      spdDC: 'Descărcător de supratensiuni c.c. (SPD) tip 2',
      discDC: 'Separator de sarcină c.c.',
      mcb: 'Disjunctor c.a. (MCB)',
      rcd: 'Protecție diferențială (RCD/RCCB)',
      spdAC: 'Descărcător de supratensiuni c.a. (SPD) tip 2',
    },
    manualNote: '(se completează manual de către proiectant / ofertant)',
    foot: 'Notă: cantitățile de cablu includ un adaos de 10% pentru rezervă și traseu. Ratingurile siguranțelor și ale disjunctoarelor se preiau din capitolul de protecții.',
  },

  anexa1: {
    title: 'ANEXA 1 - BREVIAR DE CALCUL CEF (PRODUCȚIE ESTIMATĂ)',
    introModel: 'Producția de energie a CEF a fost estimată cu instrumentul propriu de calcul (modele documentate: Hofierka/Suri 2002 - cer senin, transpoziție anisotropică PVGIS-nativă, derating termic pe suprafața de eficiență Huld 2010, pierderi unghiulare Martin-Ruiz; acuratețe documentată față de PVGIS). Unde este disponibil, se prezintă și comparația cu datele oficiale PVGIS (SARAH) importate per șir.',
    introOfficial: 'Producția de energie a CEF provine din DATELE OFICIALE PVGIS (Comisia Europeană / JRC, baza {dbinfo}), importate per șir din raportul PVGIS al fiecărei orientări. Valorile lunare și anuale prezentate mai jos sunt cele oficiale PVGIS.',
    introMixed: 'Pentru șirurile {offList}, producția provine din DATELE OFICIALE PVGIS (Comisia Europeană / JRC, baza {dbinfo}), importate per șir. Pentru celelalte șiruri ({modList}), producția a fost estimată cu instrumentul propriu de calcul (modele documentate: Hofierka/Suri 2002 - cer senin, transpoziție anisotropică PVGIS-nativă, derating termic pe suprafața de eficiență Huld 2010, pierderi unghiulare Martin-Ruiz; acuratețe documentată față de PVGIS).',
    mProd:   'Producție anuală estimată',
    mKwp:    'Putere instalată',
    mSpec:   'Producție specifică',
    mAvg:    'Medie lunară',
    cProd:   'Producția lunară de energie [kWh]',
    cDaily:  'Curbă zilnică de producție (cer senin)',
    cCvsP:   'Producție vs. consum lunar [kWh]',
    cTable:  'Tabel date lunare',
    tCols:   ['Luna', 'Energie [kWh]', 'Consum [kWh]', 'Relativ'],
    tAnual:  'Anual',
    lossTitle: 'Pierderi de putere pe conductoare',
    lossIntro: 'Pierderile de putere pe conductoare se calculează pe tronsoane, cu relațiile ΔP = 2·R·I² pe partea de curent continuu și monofazat, respectiv ΔP = 3·R·I² pe partea trifazată, unde R = ρ·l/S. Valorile se însumează și se raportează la puterile nominale.',
    lossCols: ['Tronson', 'L [m]', 'S [mm²]', 'R [Ω]', 'I [A]', 'ΔP [W]'],
    lossTot: 'Total pierderi pe conductoare: c.c. {dcw} W ({dcpct} % din puterea instalată c.c.), c.a. {acw} W ({acpct} % din puterea c.a.), total {totw} W.',
    lossNote: 'Pierderile de mai sus sunt strict cele pe conductoare. Randamentul global al sistemului rezultă din compunerea acestora cu randamentul de conversie al invertorului, conform fișei tehnice a acestuia.',
    brevTitle: 'Breviar de calcul - dimensionarea șirurilor',
    brevIntro: 'Numărul de module conectate în serie se stabilește astfel încât tensiunea de circuit deschis a șirului, la temperatura minimă de calcul a celulei, să nu depășească tensiunea maximă de intrare a invertorului, iar tensiunea în punctul de putere maximă, la temperatura maximă a celulei, să rămână în plaja de lucru MPPT. Temperatura celulei se determină din temperatura aerului și NMOT, cu toleranța de ±3% a NMOT. Calculul se prezintă mai jos pentru fiecare șir, cu datele de catalog ale modulului și ale invertorului alese.',
    brevCols: ['Mărime', 'Relație de calcul', 'Substituire numerică', 'Rezultat'],
    brevLbl: {
      tcmin:  'Temperatura celulei, minimă',
      tcmax:  'Temperatura celulei, maximă',
      vocmax: 'Tensiunea de circuit deschis a modulului, maximă (la Tc,min)',
      vmpmin: 'Tensiunea MPP a modulului, minimă (la Tc,max)',
      iscmax: 'Curentul de scurtcircuit al modulului, maxim',
      impmax: 'Curentul MPP al modulului, maxim',
      vocstr: 'Tensiunea de circuit deschis a șirului',
    },
    brevNs: 'Rezultă Ns,min = {nsmin} module și Ns,max = {nsmax} module în serie; configurația adoptată are Ns = {ns} module în serie și Np = {np} șir(uri) în paralel (Np,max admis = {npmax}).',
    brevOk:  'Verificare: Voc,șir = {vocstr} V ≤ Umax,cc invertor = {vinvmax} V; Imp,max = {impmax} A ≤ Imax,MPPT = {impptmax} A; Isc,max = {iscmax} A ≤ Isc,MPPT = {iscmppt} A. Configurația respectă limitele invertorului.',
    brevBad: 'ATENȚIE: configurația adoptată NU respectă în totalitate limitele invertorului (Voc,șir = {vocstr} V față de Umax,cc = {vinvmax} V; Imp,max = {impmax} A față de {impptmax} A; Isc,max = {iscmax} A față de {iscmppt} A). Se impune revizuirea numărului de module în serie/paralel.',
    bdTitle: 'Defalcare pe șiruri',
    bdCols:  ['Șir', 'Modul', 'Module', 'kWp', 'Încl./Az. [°]', 'PR', 'kWh/an', 'kWh/kWp'],
    pvgisTag:'date PVGIS (oficial)',
  },

  planse: {
    title: 'PLANȘE',
    note: 'Planșele de mai jos fac parte din documentație și se anexează (elaborate CAD, conform borderoului). Cartușul fiecărei planșe va conține datele de identificare de mai jos.',
    cartus: { desenat: 'Desenat', proiectat: 'Proiectat', aprobat: 'Aprobat', faza: 'Faza', scara: 'Scara', plansa: 'Planșa' },
    seAnexeaza: 'SE ANEXEAZĂ - planșă elaborată separat',
    schemaMissing: 'Schema monofilară nu poate fi generată - completați șirurile, modulele și invertorul în pașii anteriori.',
    viewSide: 'Secțiune laterală - la scară',
    viewPlan: 'Vedere de sus - la scară',
    noPlan: 'Vederea de sus necesită dimensiunile suprafeței de montaj (lățime și adâncime) din pasul Montaj.',
  },
};
