/* temp-png.js — temperature PNG loader.
   Decodes data/temp5.png (or data/temperature.png) generated by
   scripts/generate-temperature-png.js.

   PNG layout:  width = NLONS × NMONTHS (73 × 12 = 876), height = NLATS (37)
                Row r = lat index; within row: col [mo*73 + c] = month mo, lon c.
                (horizontal layout — months side-by-side — compresses better than stacked)
   Encoding:    pixel = temp_°C + 128
   Decode:      temp_°C = pixel − 128

   Cell access after decode (output array unchanged from callers' perspective):
     temp[m][r][c] = data[(m * NLATS + r) * NLONS + c]   (signed °C)
   where r = 0 → LAT_MIN (−90°), m = 0 → January.

   Returns Promise<Int8Array> of length NMONTHS × NLATS × NLONS. */

async function loadTemperaturePng(url, headers = {}) {
  /* ── 1. Fetch ── */
  const resp = await fetch(url, { headers });
  if (!resp.ok) throw new Error(`loadTemperaturePng: HTTP ${resp.status} for ${url}`);
  const buf  = await resp.arrayBuffer();
  const view = new DataView(buf);
  const u8   = new Uint8Array(buf);

  /* ── 2. PNG dimensions from IHDR ── */
  const width   = view.getUint32(16);   // NLONS × NMONTHS
  const height  = view.getUint32(20);   // NLATS
  const NMONTHS = 12, NLATS = height, NLONS = width / NMONTHS;

  /* ── 3. Collect IDAT ── */
  const idatParts = [];
  let obfuscated = false;                     // set if the PNG carries the 'obf' tEXt marker
  let pos = 33;
  while (pos + 8 <= buf.byteLength) {
    const chunkLen  = view.getUint32(pos);
    const chunkType = String.fromCharCode(u8[pos+4], u8[pos+5], u8[pos+6], u8[pos+7]);
    if (chunkType === 'IEND') break;
    if (chunkType === 'IDAT') idatParts.push(u8.slice(pos + 8, pos + 8 + chunkLen));
    else if (chunkType === 'tEXt' && u8[pos+8] === 111 && u8[pos+9] === 98 && u8[pos+10] === 102) obfuscated = true;
    pos += 4 + 4 + chunkLen + 4;
  }

  /* ── 4. Concatenate IDAT ── */
  const idatLen = idatParts.reduce((s, c) => s + c.length, 0);
  const idat    = new Uint8Array(idatLen);
  let off = 0;
  for (const part of idatParts) { idat.set(part, off); off += part.length; }

  /* ── 5. Decompress (zlib DEFLATE, RFC 1950 — standard PNG) ── */
  const stream = new Blob([idat]).stream().pipeThrough(new DecompressionStream('deflate'));
  const rawBuf = await new Response(stream).arrayBuffer();
  const raw    = new Uint8Array(rawBuf);

  /* ── 6. Reconstruct Sub filter → raw W×H raster ── */
  const scanStride = 1 + width;
  let img = new Uint8Array(width * height);
  for (let r = 0; r < height; r++) {
    const base = r * scanStride;
    let prev = 0;
    for (let col = 0; col < width; col++) {
      const px = (raw[base + 1 + col] + prev) & 0xFF;
      prev = px;
      img[r * width + col] = px;
    }
  }

  /* ── 6b. Reverse the grid obfuscation (only when the PNG is marked) ── */
  if (obfuscated) {
    if (typeof GridObfus === 'undefined') throw new Error('loadTemperaturePng: grid-deshuffle.js must load before an obfuscated grid');
    img = GridObfus.decode(img, width, height);
  }

  /* ── 6c. PNG col = mo*NLONS+c → canonical (mo*NLATS+r)*NLONS+c ── */
  const result = new Int8Array(NMONTHS * NLATS * NLONS);
  for (let r = 0; r < NLATS; r++) {
    for (let col = 0; col < width; col++) {
      const mo = Math.floor(col / NLONS);
      const c  = col % NLONS;
      result[(mo * NLATS + r) * NLONS + c] = img[r * width + col] - 128;   // unsigned pixel → signed °C
    }
  }

  return result;  // Int8Array, index: (m * NLATS + r) * NLONS + c, decode: temp = value (°C)
}
